/*! @file
 * @brief A Propagator class for binary systems of massive objects
 *
 * @author Federico Ragno
 */
#pragma once

#include <cstdint>
#include <cstdio>

#include "cstone/fields/field_get.hpp"
#include "io/arg_parser.hpp"
#include "ipropagator.hpp"
#include "std_hydro.hpp"
#include "sph/particles_data.hpp"
#include "sph/sph.hpp"

#include "accretion.hpp"
#include "beta_cooling.hpp"
#include "binary_energy.hpp"
#include "central_force.hpp"
#include "exchange_star_position.hpp"
#include "star_data.hpp"
#include "reciprocal_force.hpp"
#include "binary_data.hpp"


namespace sphexa
{

using namespace sph;
using util::FieldList;

template<class DomainType, class DataType>
class BinaryProp : public HydroProp<DomainType, DataType>
{
protected:
    using Base = HydroProp<DomainType, DataType>;
    using Base::timer;

    using T = typename DataType::RealType;

    disk::StarData star1;
    disk::StarData star2;

public:
    BinaryProp(std::ostream& output, size_t rank, const InitSettings& settings) // Settings are not used!
        : Base(output, rank)
    {
    }

    void load(const std::string& initCond, IFileReader* reader) override
    {
        // Read star position from hdf5 File

        //FR: strips runtime modifiers separated by ":" from input path. Eg: if initCond is "disk.h5:10", path is "disk.h5"
        std::string path = removeModifiers(initCond);

        //FR: checks whether file associated with path exists. In test cases (eg: initCond = "evrard") star data will not be loaded because it doesn't come from a file
        if (std::filesystem::exists(path))
        {
            /*FR: Determines which snapshot in the h5 file to read initial conditions from.
            Initial conditions file format:
                disk.h5
                ├── Step#0
                ├── Step#1
                ├── Step#2
                ...
                ├── Step#10
            If initCont = "disk.h5:10" initial conditions will be taken from 10th timestep
            */
            int snapshotIndex = numberAfterSign(initCond, ":");
            reader->setStep(path, snapshotIndex, FileMode::independent);

            star1.loadOrStoreAttributes(reader, "star1");
            star2.loadOrStoreAttributes(reader, "star2");

            reader->closeStep();

            //FR Ensure binary is physically consistent
            if( ! binary_is_consistent(star1, star2) ) { 
                throw std::runtime_error("Binary propagator initialization error: star binary is not consistent" );
            }

            std::printf("star 1 position: %lf\t%lf\t%lf\n", star1.position[0], star1.position[1], star1.position[2]);
            std::printf("star 1 mass: %lf\n", star1.m);
            std::printf("star 2 position: %lf\t%lf\t%lf\n", star2.position[0], star2.position[1], star2.position[2]);
            std::printf("star 2 mass: %lf\n", star2.m);

        }
    }

    void save(IFileWriter* writer) override
    {
        star1.loadOrStoreAttributes(writer, "star1");
        star2.loadOrStoreAttributes(writer, "star2");
    }

    /* First key function in binarypropagator. Includes:
    In Hydroprop
        1) Domain synchronization
        2) Density evaluation
        3) Thermodynamic parameters evaluation (P, c, T) via chosen EOS
        4) Evaluation and writing of: acceleration; energy; courant-limited timestep
    In binaryprop
        5) Beta cooling
        6) Binary-disk; binary-binary forces
    */
    void computeForces(DomainType& domain, DataType& simData) override
    {
        Base::computeForces(domain, simData);               // compute hydro forces

        auto&        d     = simData.hydro;                 //FR: alias to hydrodynamical particle fields
        const size_t first = domain.startIndex();
        const size_t last  = domain.endIndex();

        disk::betaCoolingBinary(first, last, d, star1, star2); //FR: Compute beta cooling centered at the binary COM

        timer.step("betaCooling");

        disk::computeCentralForce(first, last, d, star1);   //FR: Compute force generated by central object, affecting accelerations of particles
        disk::computeCentralForce(first, last, d, star2);
        timer.step("computeCentralForce");

        // TODO (not stringent): einstein precession
        disk::computeBinaryForce(star1, star2, d);          //FR computes the forces between the stars
        timer.step("computeBinaryForce");
    }

    /* Second key function of binarypropagator. Includes:

    */
    void integrate(DomainType& domain, DataType& simData) override
    {
        const size_t first = domain.startIndex();
        const size_t last  = domain.endIndex();
        auto&        d     = simData.hydro;
        
        /*FR:
        Compute a maximal timestep based on how fast the internal energy changes.
        Writes: star.t_du
        */
        disk::duTimestep(first, last, d, star1);
        star2.t_du = star1.t_du;
        timer.step("duTimestep");
        
        /*FR:
        Computes global d.minDT with the standard SPH limits plus two extra limits coming from the disk:
            1) star.t_du: cooling rate limit
            2) d.etaAcc * star.t_star: central force acceleration limit
        
        Selects most restrictive physical timescale out of:
            1) CFL                      dt ~ dx / (c_s + v_signal)
            2) acceleration-based       dt ~ a / a_dot
            3) density-based            dt ~ rho / rho_dot
            4) energy-based             dt ~ u / u_dot
            5) gravity-based            dt ~ sqrt(r_min^3 / GM)
        
        TODO (not stringent): need to add a binary orbital period!
        */
        computeTimestep(first, last, d, 
            star1.t_du,
            d.etaAcc * star1.t_star,
            d.etaAcc * star2.t_star
        );
        timer.step("Timestep");

        /*FR:
        Integrates particle positions and velocities using ax, ay, az over timestep d.minDt
        Integrates thermal state using du over timestep d.minDt
        */
        computePositions(Base::groups_.view(), d, domain.box(), d.minDt, {float(d.minDt_m1)});
        {
            uint64_t local_count  = disk::applyEnergyFloor(first, last, d);
            uint64_t global_count = 0;
            MPI_Allreduce(&local_count, &global_count, 1, MPI_UINT64_T, MPI_SUM, MPI_COMM_WORLD);
            if (Base::rank_ == 0)
                std::printf("Energy floor: %llu particles clamped to u_inf/10\n",
                            static_cast<unsigned long long>(global_count));
        }
        timer.step("applyEnergyFloor");

        //FR: updates smoothing length of each particle to reach target number of neighbors ng0
        updateSmoothingLength(Base::groups_.view(), d);
        timer.step("UpdateQuantities");

        /*FR:
            1) Collects gravitational reaction forces from all MPI ranks for both stars
            2) Computes star potentials and energies (before position update, so KE = v_{n+1/2}^2)
            3) Integrates both stars’ positions
        */
        disk::computeAndExchangeBinaryPositions(star1, star2, d);
        timer.step("computeAndExchangeBinaryPositions");

        /*FR:
        Determines which particles:
            1) Fall inside accretion radius -> accrete them to star
            2) Become numerically problematic -> remove them
        Also tracks accretion and removal statistics (mass, momentum) to ensure conservation properties
        
        Practically: removes particles and writes:
            star.accreted_local (stores accretion statistics at given timestep)
            star.removed_local (stores removal statistics at given timestep)

            DOES NOT MODIFY STAR'S MASS OR MOMENTUM YET (see below)
        */
        disk::computeAccretionCondition(first, last, d, star1);
        disk::computeAccretionCondition(first, last, d, star2);
        timer.step("computeAccretionCondition");

        //disk::computeBinaryAccretionCondition(star1, star2); //TODO: check if stars have merged (?)

        /*FR: TODO -> add spin to star?
            1) Collects accreted mass and momentum from all MPI ranks
            2) Adds mass and momentum to star
        */
        disk::exchangeAndAccreteOnStar(star1, d.minDt_m1, Base::rank_);
        disk::exchangeAndAccreteOnStar(star2, d.minDt_m1, Base::rank_);
        timer.step("exchangeAndAccreteOnStar");

        if (Base::rank_ == 0)
        {
            std::printf("star 1 position: %lf\t%lf\t%lf\n", star1.position[0], star1.position[1], star1.position[2]);
            std::printf("star 1 mass: %lf\n", star1.m);
            std::printf("additional pot. erg. 1: %lf\n", star1.potential);

            std::printf("star 2 position: %lf\t%lf\t%lf\n", star2.position[0], star2.position[1], star2.position[2]);
            std::printf("star 2 mass: %lf\n", star2.m);
            std::printf("additional pot. erg. 2: %lf\n", star2.potential);
        }

    }

    void printIterationTimings(const DomainType& domain, const DataType& simData) override
    {
        if (Base::rank_ == 0)
        {
            const auto& d = simData.hydro;
            this->out << "### Check ### Star 1 energy: " << star1.etot
                      << ", (kinetic: " << star1.ecin << ", potential: " << star1.egrav << ")\n";
            this->out << "### Check ### Star 2 energy: " << star2.etot
                      << ", (kinetic: " << star2.ecin << ", potential: " << star2.egrav << ")\n";
            this->out << "### Check ### Total energy (disk + stars): "
                      << d.etot + star1.etot + star2.etot << "\n";
        }
        Base::printIterationTimings(domain, simData);
    }

};

} // namespace sphexa