/*! @file
 * @brief A Propagator class for binary systems of massive objects
 *
 * @author Federico Ragno
 */
#pragma once

#include <cstdio>

#include "cstone/fields/field_get.hpp"
#include "io/arg_parser.hpp"
#include "ipropagator.hpp"
#include "std_hydro.hpp"
#include "sph/particles_data.hpp"
#include "sph/sph.hpp"

#include "accretion.hpp"
#include "beta_cooling.hpp"
#include "central_force.hpp"
#include "exchange_star_position.hpp"
#include "star_data.hpp"
#include "reciprocal_force.hpp"
#include "binary_data.hpp"


namespace sphexa
{

using namespace sph;
using util::FieldList;

template<class DomainType, class DataType>
class BinaryProp : public HydroProp<DomainType, DataType>
{
protected:
    using Base = HydroProp<DomainType, DataType>;
    using Base::timer;

    using T = typename DataType::RealType;

    disk::StarData star1;
    disk::StarData star2;

public:
    BinaryProp(std::ostream& output, size_t rank, const InitSettings& settings) // Settings are not used!
        : Base(output, rank)
    {
    }

    void load(const std::string& initCond, IFileReader* reader) override
    {
        std::string path = removeModifiers(initCond);

        if (std::filesystem::exists(path))
        {
            int snapshotIndex = numberAfterSign(initCond, ":");
            reader->setStep(path, snapshotIndex, FileMode::independent);

            star1.loadOrStoreAttributes(reader, "star1");
            star2.loadOrStoreAttributes(reader, "star2");

            reader->closeStep();

            if( ! binary_is_consistent(star1, star2) ) { 
                throw std::runtime_error("Binary propagator initialization error: star binary is not consistent" );
            }

            std::printf("star 1 position: %lf\t%lf\t%lf\n", star1.position[0], star1.position[1], star1.position[2]);
            std::printf("star 1 mass: %lf\n", star1.m);
            std::printf("star 2 position: %lf\t%lf\t%lf\n", star2.position[0], star2.position[1], star2.position[2]);
            std::printf("star 2 mass: %lf\n", star2.m);

        }
    }

    void save(IFileWriter* writer) override
    {
        star1.loadOrStoreAttributes(writer, "star1");
        star2.loadOrStoreAttributes(writer, "star2");
    }

    //TODO compute forces function
    void computeForces(DomainType& domain, DataType& simData) override
    {
        Base::computeForces(domain, simData);

        auto&        d     = simData.hydro;         // alias to hydrodynamical particle fields
        const size_t first = domain.startIndex();   
        const size_t last  = domain.endIndex();

        // TODO (not stringent): COOLING - THIS MIGHT REQUIRE MODIFICATION DUE TO DIFFERENT PHYSICS!!!
        disk::betaCooling(first, last, d, star1);    //FR: Compute beta cooling, affecting du
        disk::betaCooling(first, last, d, star2);
        timer.step("betaCooling");

        disk::computeCentralForce(first, last, d, star1);    //FR: Compute force generated by central object, affecting accelerations of particle
        disk::computeCentralForce(first, last, d, star2);
        timer.step("computeCentralForce");

        // TODO (not stringent): einstein precession
        disk::computeBinaryForce(star1, star2, d);  // computes the forces between the stars
        timer.step("computeBinaryForce");
    }

    //TODO (not stringent) integrate function
    void integrate(DomainType& domain, DataType& simData) override
    {
        const size_t first = domain.startIndex();
        const size_t last  = domain.endIndex();
        auto&        d     = simData.hydro;

        disk::duTimestep(first, last, d, star1);
        disk::duTimestep(first, last, d, star2);
        timer.step("duTimestep");
        
        // TODO (not stringent): need to add a binary orbital period!
        computeTimestep(first, last, d, 
            star1.t_du,
            star2.t_du,
            d.etaAcc * star1.t_star,
            d.etaAcc * star2.t_star
        );
        timer.step("Timestep");

        // Integrate particle positions and thermal state
        computePositions(Base::groups_.view(), d, domain.box(), d.minDt, {float(d.minDt_m1)});
        updateSmoothingLength(Base::groups_.view(), d);
        timer.step("UpdateQuantities");

        disk::computeAndExchangeStarPosition(star1, d.minDt, d.minDt_m1);
        disk::computeAndExchangeStarPosition(star2, d.minDt, d.minDt_m1);
        timer.step("computeAndExchangeStarPosition");

        disk::computeAccretionCondition(first, last, d, star1);
        disk::computeAccretionCondition(first, last, d, star2);
        timer.step("computeAccretionCondition");

        //disk::computeBinaryAccretionCondition(star1, star2); //TODO: check if stars have merged (?)

        disk::exchangeAndAccreteOnStar(star1, d.minDt_m1, Base::rank_);
        disk::exchangeAndAccreteOnStar(star2, d.minDt_m1, Base::rank_);
        timer.step("exchangeAndAccreteOnStar");

        //disk::mergeStars() //TODO: merge stars (?)

        if (Base::rank_ == 0)
        {
            std::printf("star 1 position: %lf\t%lf\t%lf\n", star1.position[0], star1.position[1], star1.position[2]);
            std::printf("star 1 mass: %lf\n", star1.m);
            std::printf("additional pot. erg. 1: %lf\n", star1.potential);

            std::printf("star 2 position: %lf\t%lf\t%lf\n", star2.position[0], star2.position[1], star2.position[2]);
            std::printf("star 2 mass: %lf\n", star2.m);
            std::printf("additional pot. erg. 2: %lf\n", star2.potential);
        }

    }

};

} // namespace sphexa