
/*! @file
 * @brief A Propagator class for Protoplanetary disk
 *
 * @author Noah Kubli
 */

#pragma once

#include <cstdio>

#include "cstone/fields/field_get.hpp"
#include "io/arg_parser.hpp"
#include "ipropagator.hpp"
#include "std_hydro.hpp"
#include "sph/particles_data.hpp"
#include "sph/sph.hpp"

#include "accretion.hpp"
#include "beta_cooling.hpp"
#include "central_force.hpp"
#include "exchange_star_position.hpp"
#include "star_data.hpp"

namespace sphexa
{

using namespace sph;
using util::FieldList;

template<class DomainType, class DataType>
class DiskProp : public HydroProp<DomainType, DataType>
{
protected:
    using Base = HydroProp<DomainType, DataType>;
    using Base::timer;

    using T = typename DataType::RealType;

    disk::StarData star;

public:
    DiskProp(std::ostream& output, size_t rank, const InitSettings& settings)
        : Base(output, rank)
    {
    }

    void load(const std::string& initCond, IFileReader* reader) override
    {
        // Read star position from hdf5 File

        //FR: strips runtime modifiers separated by ":" from input path. Eg: if initCond is "disk.h5:10", path is "disk.h5"
        std::string path = removeModifiers(initCond);
        
        //FR: checks whether file associated with path exists. In test cases (eg: initCond = "evrard") star data will not be loaded because it doesn't come from a file
        if (std::filesystem::exists(path))
        {
        
            /*FR: Determines which snapshot in the h5 file to read initial conditions from.
            Initial conditions file format:
                disk.h5
                ├── Step#0
                ├── Step#1
                ├── Step#2
                ...
                ├── Step#10
            If initCont = "disk.h5:10" initial conditions will be taken from 10th timestep
            */
            int snapshotIndex = numberAfterSign(initCond, ":");
            reader->setStep(path, snapshotIndex, FileMode::independent);
            star.loadOrStoreAttributes(reader);
            reader->closeStep();
            std::printf("star position: %lf\t%lf\t%lf\n", star.position[0], star.position[1], star.position[2]);
            std::printf("star mass: %lf\n", star.m);
        }
    }
    void save(IFileWriter* writer) override { star.loadOrStoreAttributes(writer); }

    void computeForces(DomainType& domain, DataType& simData) override
    {
        Base::computeForces(domain, simData);

        auto&        d     = simData.hydro;                 //FR: alias to hydrodynamical particle fields
        const size_t first = domain.startIndex();
        const size_t last  = domain.endIndex();

        disk::betaCooling(first, last, d, star);            //FR: Compute beta cooling, affecting du
        timer.step("betaCooling");

        disk::computeCentralForce(first, last, d, star);    //FR: Compute force generated by central object, affecting accelerations of particle
        timer.step("computeCentralForce");
    }

    //FR: single timestep - updates fields
    void integrate(DomainType& domain, DataType& simData) override
    {
        const size_t first = domain.startIndex();
        const size_t last  = domain.endIndex();
        auto&        d     = simData.hydro;

        /*FR:
        Compute a maximal timestep based on how fast the internal energy changes.
        Writes: star.t_du
        */
        disk::duTimestep(first, last, d, star);
        timer.step("duTimestep");

        /*FR:
        Computes global d.minDT with the standard SPH limits plus two extra limits coming from the disk:
            1) star.t_du: cooling rate limit
            2) d.etaAcc * star.t_star: central force acceleration limit
        
        Selects most restrictive physical timescale out of:
            1) CFL                      dt ~ dx / (c_s + v_signal)
            2) acceleration-based       dt ~ a / a_dot
            3) density-based            dt ~ rho / rho_dot
            4) energy-based             dt ~ u / u_dot
            5) gravity-based            dt ~ sqrt(r_min^3 / GM)
        */
        computeTimestep(first, last, d, star.t_du, d.etaAcc * star.t_star);
        timer.step("Timestep");

        /*FR:
        Integrates particle positions and velocities using ax, ay, az over timestep d.minDt
        Integrates thermal state using du over timestep d.minDt
        */
        computePositions(Base::groups_.view(), d, domain.box(), d.minDt, {float(d.minDt_m1)});
        
        //FR: updates smoothing length of each particle to reach target number of neighbors ng0
        bool haveUnconvergedParticles = updateSmoothingLength(Base::groups_.view(), d);
        if (haveUnconvergedParticles && not d.removeUnconvergedParticles)
        {
            throw std::runtime_error("Neighbor search did not converge\n");
        }
        timer.step("UpdateQuantities");

        /*FR:
            1) Collects gravitational reaction forces from all MPI ranks
	        2) Computes the star’s acceleration and potential
	        3) Integrates its motion, updating star’s position
        */
        disk::computeAndExchangeStarPosition(star, d.minDt, d.minDt_m1);
        timer.step("computeAndExchangeStarPosition");

        /*FR:
        Determines which particles:
            1) Fall inside accretion radius -> accrete them to star
            2) Become numerically problematic -> remove them
        Also tracks accretion and removal statistics (mass, momentum) to ensure conservation properties
        
        Practically: removes particles and writes:
            star.accreted_local (stores accretion statistics at given timestep)
            star.removed_local (stores removal statistics at given timestep)

            DOES NOT MODIFY STAR'S MASS OR MOMENTUM
        */
        disk::computeAccretionCondition(first, last, d, star);
        timer.step("computeAccretionCondition");

        /*FR:
            1) Collects accreted mass and momentum from all MPI ranks
            2) Adds mass and momentum to star
        */
        disk::exchangeAndAccreteOnStar(star, d.minDt_m1, Base::rank_);
        timer.step("exchangeAndAccreteOnStar");

        if (Base::rank_ == 0)
        {
            std::printf("star position: %lf\t%lf\t%lf\n", star.position[0], star.position[1], star.position[2]);
            std::printf("star mass: %lf\n", star.m);
            std::printf("additional pot. erg.: %lf\n", star.potential);
        }
    }
};

} // namespace sphexa
